### ISSUE TITLE
cant view .sc / .scd files

### ISSUE THREAD

**Issue by catfact** [monome/maiden#219] opened 2022-03-21 04:13 UTC
this is a weird one, i dont remember seeing it before?

seleting a .sc file in maiden makes the UI show the "thinking" animation for a long moment, then displays a blank editor:

<img width="676" alt="image" src="https://user-images.githubusercontent.com/94855/159204491-55e7d6d8-973c-4ff2-998d-55baff3ac1b4.png">

(the file exists:)

<img width="463" alt="image" src="https://user-images.githubusercontent.com/94855/159204473-575c519b-e5af-42be-910d-053ba2124e96.png">

**Comment by ngwese** [comment] 2022-03-21 14:01
If I had to guess this might have been broken around the time audio file preview was added.

**Comment by ngwese** [comment] 2022-03-22 03:47
Super weird. This seems to only happen on the latest image. The same build on an older image or running remotely (and accessing norns via sshfs) does not exhibit the problem.

**Comment by ngwese** [comment] 2022-03-22 04:02
The backend is serving the file in full. On older images (or macOS) the reported content type for the file is:

**Comment by ngwese** [comment] 2022-03-22 04:46
The root cause is still not clear but the problem seems to be that `http.DetectContetType(...)` (https://cs.opensource.google/go/go/+/refs/tags/go1.18:src/net/http/sniff.go;l=21) is producing a different result on the new OS. The `maiden` backend is using the `gin` framework's `context.File` function to return the file contents. That function in turn is a minimal wrapper around `http.ServerFile` which itself leans on `http.DeteContentType` to set the header.

**Comment by ngwese** [comment] 2022-03-22 05:45
The root cause is that if a file path is supplied to `http.ServeFile` and the extension on that file appears in `/etc/mime.types` then the mime type entry is used to set the `Content-Type` for the request. The previous debian stretch based image did not have an entry for `sc` but the bullseye image contains an entry for `sc` which maps it to `application/vnd.ibm.secure-container`. The net result is that the editor doesn't believe the file is text a falls back to (confusingly) displaying an empty editor.

**Comment by ngwese** [comment] 2022-03-22 06:30
Unfortunately there is no way to override the default behavior of using the extension to dictate the mime type other than hard coding knowledge of `.sc` files into maiden itself.

fixed as of c516419ebbaf6c4c0ea4db207bfb98efb0c62af5

**Closed by ngwese** 2022-03-22 06:30 UTC
